"""campos que faltaban de auditoria en las tablas user y user_session

Revision ID: 2b5779af20b5
Revises: 3e3264987325
Create Date: 2026-01-15 22:41:41.381950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b5779af20b5'
down_revision: Union[str, Sequence[str], None] = '3e3264987325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_genres_name', 'genres', ['name'], unique=False)
    op.add_column('user_sessions', sa.Column('modificated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user_sessions', sa.Column('habilited', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('user_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'favorite_genres')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_genres', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user_sessions', 'deleted_at')
    op.drop_column('user_sessions', 'habilited')
    op.drop_column('user_sessions', 'modificated_at')
    op.drop_index('ix_genres_name', table_name='genres')
    # ### end Alembic commands ###
