"""quito columna status en auth session

Revision ID: 5fa49757e640
Revises: 8767647e3466
Create Date: 2026-02-02 21:41:48.850245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5fa49757e640'
down_revision: Union[str, Sequence[str], None] = '8767647e3466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_sessions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('status', mysql.VARCHAR(length=16), nullable=False))
    # ### end Alembic commands ###
