"""bug fixing

Revision ID: 6ed5e6d887c3
Revises: 2b5779af20b5
Create Date: 2026-01-15 22:51:14.316090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ed5e6d887c3'
down_revision: Union[str, Sequence[str], None] = '2b5779af20b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'deleted_at')
    op.drop_column('user_sessions', 'habilited')
    op.drop_column('user_sessions', 'created_at')
    op.drop_column('user_sessions', 'modificated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('modificated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False))
    op.add_column('user_sessions', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.add_column('user_sessions', sa.Column('habilited', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('user_sessions', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
