"""diversos fixes

Revision ID: 8767647e3466
Revises: 4c39b36cdf9a
Create Date: 2026-01-30 19:12:58.441594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8767647e3466'
down_revision: Union[str, Sequence[str], None] = '4c39b36cdf9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_session_tokens', sa.Column('token_jti', sa.String(length=64), nullable=False))
    op.drop_index(op.f('uq_auth_session_tokens_token_hash'), table_name='auth_session_tokens')
    op.create_unique_constraint(op.f('uq_auth_session_tokens_token_jti'), 'auth_session_tokens', ['token_jti'])
    op.drop_column('auth_session_tokens', 'token_hash')
    op.add_column('auth_sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('auth_sessions', sa.Column('accept_language', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_auth_sessions_user_id_users'), 'auth_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('auth_sessions', 'device_fingerprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('device_fingerprint', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(op.f('fk_auth_sessions_user_id_users'), 'auth_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_column('auth_sessions', 'accept_language')
    op.drop_column('auth_sessions', 'user_id')
    op.add_column('auth_session_tokens', sa.Column('token_hash', mysql.VARCHAR(length=64), nullable=False))
    op.drop_constraint(op.f('uq_auth_session_tokens_token_jti'), 'auth_session_tokens', type_='unique')
    op.create_index(op.f('uq_auth_session_tokens_token_hash'), 'auth_session_tokens', ['token_hash'], unique=True)
    op.drop_column('auth_session_tokens', 'token_jti')
    # ### end Alembic commands ###
